name: Build Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    outputs:
      coverage: ${{ steps.extract_coverage.outputs.coverage_summary }}
      result: ${{ job.status }}
    permissions:
      checks: write
      pull-requests: write
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Jest Coverage Report
        id: coverage
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          output: report-markdown

      - name: Extract Coverage Summary
        id: extract_coverage
        run: |
          REPORT="${{ steps.coverage.outputs.report }}"
          # Extract lines after "## Coverage" and before the next section
          SUMMARY=$(echo "$REPORT" | sed -n '/^## Coverage/,/^##/p' | grep -v '^##')
          # Remove HTML comments
          SUMMARY=$(echo "$SUMMARY" | grep -v '<!--')
          # Trim whitespace
          SUMMARY=$(echo "$SUMMARY" | awk '{$1=$1};1')
          echo "coverage_summary<<EOF" >> $GITHUB_OUTPUT
          echo "$SUMMARY" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

  slack:
    permissions:
      contents: read
      actions: read
    runs-on: ubuntu-latest
    needs: test
    if: always()
    steps:
      - uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: repo,message,author,ref,pullRequest
          custom_payload: |
            {
              attachments: [{
                color: '${{needs.test.result}}' === 'success' ? 'good' : '${{needs.test.result}}' === 'failure' ? 'danger' : 'warning',
                title: 'Pull Request Result',
                text: '${{needs.test.result}}' === 'success' ? 'Test Coverage Report' : 'Tests Failed',
                fields: [
                  {
                    title: 'Result',
                    value: '${{needs.test.result}}'
                  },
                  {
                    title: 'Coverage Summary',
                    value: '${{needs.test.outputs.coverage}}',
                    short: false
                  }
                ]
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()
