name: Build Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    outputs:
      started_at: ${{ steps.start_time.outputs.time }}
      ended_at: ${{ steps.end_time.outputs.time }}
      duration: ${{ steps.duration.outputs.time }}
    permissions:
      checks: write
      pull-requests: write
      contents: write
    steps:
      - name: Record start time
        id: start_time
        run: |
          echo "time=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_OUTPUT
          echo "timestamp=$(date +%s)" >> $GITHUB_OUTPUT

      - name: Checkout
        uses: actions/checkout@v4

      - name: Jest Coverage Report
        id: coverage
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          output: report-markdown
      - name: Add coverage comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: ${{ steps.coverage.outputs.report }}

      - name: Record end time
        id: end_time
        run: |
          echo "time=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_OUTPUT
          echo "timestamp=$(date +%s)" >> $GITHUB_OUTPUT

      - name: Calculate duration
        id: duration
        run: |
          start_time=${{ steps.start_time.outputs.timestamp }}
          end_time=${{ steps.end_time.outputs.timestamp }}
          duration=$((end_time - start_time))

          # Format duration as mm:ss
          minutes=$((duration / 60))
          seconds=$((duration % 60))
          formatted_time=$(printf "%02d:%02d" $minutes $seconds)

          echo "seconds=$duration" >> $GITHUB_OUTPUT
          echo "time=$formatted_time" >> $GITHUB_OUTPUT

  send-pull-request-result-to-slack:
    permissions:
      contents: read
      actions: read
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took,pullRequest
          custom_payload: |
            {
                  text: "Pull Request on ${{ github.repository }}",
                  attachments: [{
                          title: 'GitHub Actions',
                          color: '${{ needs.test.result}}' === 'success' ? 'good' : '${{ needs.test.result }}' === 'failure' ? 'danger' : 'warning',
                          text: '${{ needs.test.result}}' === 'success' ? 'Success' : '${{ needs.test.result }}' === 'failure' ? 'Failure' : 'Warning',
                          fields: [
                              {
                                title: 'Branch',
                                value: '${{ github.event.pull_request.head.sha }}'
                              },
                              {
                                  title: 'Test Result',
                                  value: '${{ needs.test.result }}'
                              },
                              {
                                  title: 'Duration',
                                  value: '${{ needs.test.outputs.duration }}'
                              },
                              {
                                  title: 'Commit',
                                  text: '${{ github.sha }}'
                              },
                              {
                                  title: 'Workflow',
                                  value: '${{ github.workflow_sha }}'
                              },
                              {
                                  title: 'Started At',
                                  value: '${{ needs.test.outputs.started_at }}'
                              },
                              {
                                  title: 'Message',
                                  value: '${{ github.event.pull_request.body }}',
                                  short: false
                              },
                          ]
                      },
                      {
                          title: 'Message',
                          text: '${{ github.event.pull_request.body }}',
                          short: true
                      }
                  ]
              }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
        # Pick up events even if the job fails or is canceled.
        if: always()
