name: Build Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    outputs:
      coverage: ${{ steps.coverage.outputs.report }}
    permissions:
      checks: write
      pull-requests: write
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10.7.1
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Use coverage code
        uses: ArtiomTr/jest-coverage-report-action@v2
        id: coverage
        with:
          output: comment, report-markdown
          package-manager: pnpm
          test-script: pnpm test -- --coverage

      - name: Add coverage comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: ${{ steps.coverage.outputs.report }}

  slack:
    permissions:
      contents: read
      actions: read
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: repo,message,author,ref,pullRequest
          custom_payload: |
            {
                  attachments: [{
                          color: '${{needs.test.result}}' === 'success' ? 'good' : '${{needs.test.result}}' === 'failure' ? 'danger' : 'warning',
                          title: 'Pull Request Result',
                          text: '${{needs.test.result}}' === 'success' ? 'Succeeded' : 'Failed',
                          fields: [
                              {
                                  title: 'Result',
                                  value: '${{needs.test.result}}'
                              },
                              {
                                  title: 'Coverage',
                                  value: '${{needs.test.outputs.coverage}}'.toString(),
                                  short: false
                              }
                          ]
                  }]
              }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
        # Pick up events even if the job fails or is canceled.
        if: always()
